import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "bet-tracker-language";

const DICTIONARY = {
  hu: {
    dashboard: "Vezérlőpult",
    bets: "Fogadások",
    analytics: "Elemzés",
    settings: "Beállítások",
    settingsSubtitle: "Bankroll, célok és felelős fogadási limitek",
    brandSubtitle: "Bankroll és elemzés",
    settingsSaved: "Beállítások mentve",
    saveFailed: "Hiba a mentés során",
    responsibleDescription: "Figyelmeztetést kapsz, ha túlléped a beállított tét-limiteket. 0 = nincs limit.",
    logout: "Kijelentkezés",
    user: "Felhasználó",
    menu: "Menü",
    language: "Nyelv",
    english: "English",
    hungarian: "Magyar",
    loading: "Betöltés…",
    welcomeBack: "Üdv újra!",
    createAccount: "Fiók létrehozása",
    loginSubtitle: "Jelentkezz be a bankrollod követéséhez.",
    registerSubtitle: "Regisztrálj és kezdd el követni a teljesítményed.",
    name: "Név",
    password: "Jelszó",
    email: "Email",
    login: "Belépés",
    register: "Regisztráció",
    googleLogin: "Belépés Google-lel",
    googleDisabled: "A Google-bejelentkezés nincs bekapcsolva a szerveren.",
    invalidGoogleState: "Érvénytelen Google-bejelentkezés. Kérlek, próbáld újra.",
    googleTokenExchangeFailed: "Nem sikerült a Google-token cseréje.",
    googleUserInfoFailed: "Nem sikerült lekérni a Google-fiók adatait.",
    googleNetworkError: "Google-hálózati hiba.",
    googleNoEmail: "A Google-fiókhoz nem tartozik email-cím.",
    googleAuthUrlMissing: "Hiányzik a Google-bejelentkezési URL.",
    googleLoginStartFailed: "Nem sikerült elindítani a Google-bejelentkezést.",
    loginSuccess: "Sikeres belépés",
    googleLoginSuccess: "Sikeres belépés Google-lel",
    accountCreated: "Fiók létrehozva",
    loginFailed: "Sikertelen bejelentkezés",
    loginInProgress: "Bejelentkezés folyamatban…",
    loginError: "Bejelentkezési hiba: {error}",
    or: "vagy",
    noAccount: "Még nincs fiókod?",
    haveAccount: "Van már fiókod?",
    registerAction: "Regisztrálj",
    loginAction: "Lépj be",
    realTimeOverview: "Valós idejű bankroll áttekintés",
    currentBankroll: "Aktuális bankroll",
    profitGoal: "Profit cél",
    setProfitGoal: "Állíts be profit célt a Beállításokban.",
    pendingBets: "Függő fogadások",
    totalBets: "Összes fogadás",
    loadingData: "Betöltés…",
    totalRecorded: "{count} fogadás rögzítve",
    save: "Mentés",
    cancel: "Mégse",
    delete: "Törlés",
    create: "Létrehozás",
    rename: "Átnevezés",
    close: "Bezárás",
    exported: "Exportálva",
    saveReport: "Új jelentés mentése",
    savedReports: "Mentett jelentések",
    saveReportDescription: "Mentsd el az aktuális statisztikáid és fogadásaid PDF-be a fiókodba, és érd el bármely eszközről bejelentkezés után.",
    noSavedReports: "Még nincs mentett jelentés.",
    reports: "Jelentések",
    pdfDownloaded: "PDF letöltve",
    downloadReport: "Jelentés letöltése",
    importFailed: "Az importálás nem sikerült",
    importedBets: "{count} fogadás importálva",
    importSkippedRows: "{count} hibás sor kihagyva",
    import: "Import",
    newBet: "Új fogadás",
    date: "Dátum",
    sportMarket: "Sport / Piac",
    pick: "Tipp",
    stake: "Tét",
    odds: "Odds",
    result: "Eredmény",
    profit: "Profit",
    balance: "Egyenleg",
    allSports: "Minden sport",
    allResults: "Minden eredmény",
    searchHint: "Keresés tipp, piac, iroda…",
    noBets: "Nincs fogadás. Kattints az „Új fogadás” gombra a kezdéshez.",
    deleteBetTitle: "Fogadás törlése",
    deleteBetDescription: "Biztosan törölni szeretnéd ezt a fogadást? Ez a művelet nem vonható vissza.",
    reportSaved: "Jelentés elmentve a fiókodhoz",
    reportSavedFailed: "Nem sikerült elmenteni a jelentést",
    reportDeleted: "Jelentés törölve",
    reportDownloadFailed: "Letöltés sikertelen",
    createReport: "Új jelentés mentése",
    analysis: "Elemzés",
    analysisSubtitle: "Részletes teljesítmény bontások",
    refresh: "frissítés…",
    totalStaked: "Megtett tét",
    netProfit: "Nettó profit",
    avgOdds: "Átlag odds",
    bySport: "Profit sportonként",
    byMarket: "Tét megoszlás piaconként",
    noData: "Nincs elég adat.",
    noClosedBets: "Nincs lezárt fogadás.",
    profitTimeline: "Profit / Veszteség idővonal",
    sportBreakdown: "Sportonkénti bontás",
    betsCount: "Fogadások",
    capital: "Tőke",
    setCapital: "Állítsuk be a bankrollod",
    setupSubtitle: "Néhány adat a pontos statisztikákhoz és a felelős fogadáshoz.",
    startBankroll: "Kezdő bankroll",
    currencyLabel: "Pénznem",
    unitSize: "Tétegység (unit)",
    responsibleGambling: "Felelős fogadás",
    dailyLimit: "Napi tét-limit",
    weeklyLimit: "Heti tét-limit",
    startNow: "Kezdjük!",
    bankroll: "Bankroll",
    newBankroll: "Új bankroll",
    bankrollsLabel: "Bankrollok",
    renameBankroll: "Bankroll átnevezése",
    deleteBankroll: "Bankroll törlése",
    confirmDeleteBankroll: "Biztosan törlöd a(z) {name} bankrollt? Az összes hozzá tartozó fogadás is véglegesen törlődik. Ez nem vonható vissza.",
    canNotDelete: "Nem sikerült törölni",
    booked: "Bankroll létrehozva",
    renamed: "Átnevezve",
    bankRollRemoved: "Bankroll törölve",
    validationRequired: "Adj meg érvényes tétet és oddsot (pl. 1000 és 1.55)",
    validationStake: "A tét legyen 0-nál nagyobb, az odds legalább 1.00",
    dailyLimitExceeded: "Túllépted a napi tét-limitedet!",
    weeklyLimitExceeded: "Túllépted a heti tét-limitedet!",
    dailyLimitNear: "Közelítesz a napi tét-limitedhez",
    weeklyLimitNear: "Közelítesz a heti tét-limitedhez",
    betSaved: "Fogadás rögzítve",
    betUpdated: "Fogadás frissítve",
    betDeleted: "Fogadás törölve",
    addBetDetails: "Add meg a fogadás részleteit. A profit automatikusan számolódik az eredmény alapján.",
    editBet: "Fogadás szerkesztése",
    betDetails: "Tipp / esemény",
    selectionExample: "pl. Arsenal – Chelsea, hazai győzelem",
    bookmakerExample: "pl. Bet365",
    oddsExample: "pl. 1,95",
    bankrollCreateFailed: "Nem sikerült létrehozni a bankrollt",
    bankrollDeleteFailed: "Nem sikerült törölni a bankrollt",
    bankrollNameRequired: "Adj nevet a bankrollnak",
    bankrollPlaceholder: "pl. Foci kassza",
    dailyLimitExceededMessage: "Túllépted a napi tét-limitedet. Fogadj felelősséggel!",
    weeklyLimitExceededMessage: "Túllépted a heti tét-limitedet. Fogadj felelősséggel!",
    dailyLimitNearMessage: "Közelítesz a napi tét-limitedhez ({percent}%). Vigyázz a tétekkel!",
    weeklyLimitNearMessage: "Közelítesz a heti tét-limitedhez ({percent}%).",
    market: "Piac",
    bookmaker: "Fogadóiroda",
    note: "Jegyzet",
    optionalNote: "Opcionális jegyzet…",
    saveBet: "Rögzítés",
    setGoalInSettings: "Állíts be profit célt a Beállításokban.",
    profitLoss: "Profit / Veszteség",
    roi: "ROI",
    winRate: "Találati arány",
    winningStreak: "Nyerő sorozat",
    losingStreak: "Vesztő sorozat",
    bankrollCurve: "Bankroll görbe",
    profitGoalCard: "Profit cél",
    setGoalPrompt: "Állíts be profit célt a Beállításokban.",
    dailyStakeLimit: "Napi tét-limit",
    weeklyStakeLimit: "Heti tét-limit",
    yield: "Yield",
    totalSettled: "Lezárt fogadás",
    avgOdds: "Átlag odds",
    amountStaked: "megtéve",
    trade: "Tranzakció",
    new: "Új",
    editing: "Szerkesztés",
    month: "Hónap",
    year: "Év",
    period: "Időszak",
    allTime: "Teljes időszak",
    last7Days: "Utolsó 7 nap",
    last30Days: "Utolsó 30 nap",
    last90Days: "Utolsó 90 nap",
    currentMonth: "Aktuális hónap",
    currentYear: "Aktuális év",
    customRange: "Egyéni tartomány",
    tx: "db",
    sport: "Sport",
    "Labdarúgás": "Labdarúgás",
    "Kosárlabda": "Kosárlabda",
    "Tenisz": "Tenisz",
    "Jégkorong": "Jégkorong",
    "Amerikai foci": "Amerikai foci",
    "Baseball": "Baseball",
    "MMA / Ökölvívás": "MMA / Ökölvívás",
    "eSport": "eSport",
    "Egyéb": "Egyéb",
    "Meccs kimenetel": "Meccs kimenetel",
    "Hendikep": "Hendikep",
    "Over / Under": "Over / Under",
    "Mindkét csapat gólt szerez": "Mindkét csapat gólt szerez",
    "Szöglet": "Szöglet",
    "Kombi": "Kombi",
    "Függőben": "Függőben",
    "Nyert": "Nyert",
    "Vesztett": "Vesztett",
    "Fél nyerés": "Fél nyerés",
    "Fél vesztés": "Fél vesztés",
    "Érvénytelen": "Érvénytelen",
  },
  en: {
    dashboard: "Dashboard",
    bets: "Bets",
    analytics: "Analysis",
    settings: "Settings",
    settingsSubtitle: "Bankroll, goals and responsible betting limits",
    brandSubtitle: "Bankroll & Analytics",
    settingsSaved: "Settings saved",
    saveFailed: "There was a problem saving your changes",
    responsibleDescription: "You will be warned when you exceed your stake limits. Set a limit to 0 to disable it.",
    logout: "Log out",
    user: "User",
    menu: "Menu",
    language: "Language",
    english: "English",
    hungarian: "Magyar",
    loading: "Loading…",
    welcomeBack: "Welcome back!",
    createAccount: "Create account",
    loginSubtitle: "Log in to track your bankroll.",
    registerSubtitle: "Register and start tracking your performance.",
    name: "Name",
    password: "Password",
    email: "Email",
    login: "Log in",
    register: "Register",
    googleLogin: "Continue with Google",
    googleDisabled: "Google sign-in is not enabled on the server.",
    invalidGoogleState: "Invalid Google sign-in. Please try again.",
    googleTokenExchangeFailed: "Could not exchange the Google token.",
    googleUserInfoFailed: "Could not retrieve Google account details.",
    googleNetworkError: "Google network error.",
    googleNoEmail: "The Google account has no email address.",
    googleAuthUrlMissing: "The Google sign-in URL is missing.",
    googleLoginStartFailed: "Could not start Google sign-in.",
    loginSuccess: "Signed in successfully",
    googleLoginSuccess: "Signed in with Google",
    accountCreated: "Account created",
    loginFailed: "Sign-in failed",
    loginInProgress: "Signing in…",
    loginError: "Sign-in error: {error}",
    or: "or",
    noAccount: "Need an account?",
    haveAccount: "Already have an account?",
    registerAction: "Register",
    loginAction: "Log in",
    realTimeOverview: "Real-time bankroll overview",
    currentBankroll: "Current bankroll",
    profitGoal: "Profit goal",
    setProfitGoal: "Set a profit goal in Settings.",
    pendingBets: "Pending bets",
    totalBets: "Total bets",
    loadingData: "Loading…",
    totalRecorded: "{count} bets recorded",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    create: "Create",
    rename: "Rename",
    close: "Close",
    exported: "Exported",
    saveReport: "Save new report",
    savedReports: "Saved reports",
    saveReportDescription: "Save your current statistics and bets as a PDF to your account and access them from any device after signing in.",
    noSavedReports: "No saved report yet.",
    reports: "Reports",
    pdfDownloaded: "PDF downloaded",
    downloadReport: "Download report",
    importFailed: "Import failed",
    importedBets: "{count} bets imported",
    importSkippedRows: "{count} invalid rows skipped",
    import: "Import",
    newBet: "New bet",
    date: "Date",
    sportMarket: "Sport / Market",
    pick: "Pick",
    stake: "Stake",
    odds: "Odds",
    result: "Result",
    profit: "Profit",
    balance: "Balance",
    allSports: "All sports",
    allResults: "All results",
    searchHint: "Search tip, market, bookmaker…",
    noBets: "No bets yet. Click the “New bet” button to get started.",
    deleteBetTitle: "Delete bet",
    deleteBetDescription: "Are you sure you want to delete this bet? This action cannot be undone.",
    reportSaved: "Report saved to your account",
    reportSavedFailed: "Failed to save the report",
    reportDeleted: "Report deleted",
    reportDownloadFailed: "Download failed",
    createReport: "Save new report",
    analysis: "Analysis",
    analysisSubtitle: "Detailed performance breakdowns",
    refresh: "refreshing…",
    totalStaked: "Total staked",
    netProfit: "Net profit",
    avgOdds: "Average odds",
    bySport: "Profit by sport",
    byMarket: "Stake distribution by market",
    noData: "Not enough data.",
    noClosedBets: "No closed bets.",
    profitTimeline: "Profit / Loss timeline",
    sportBreakdown: "Sport breakdown",
    betsCount: "Bets",
    capital: "Capital",
    setCapital: "Set up your bankroll",
    setupSubtitle: "A few details for accurate stats and responsible betting.",
    startBankroll: "Starting bankroll",
    currencyLabel: "Currency",
    unitSize: "Unit size (unit)",
    responsibleGambling: "Responsible gambling",
    dailyLimit: "Daily stake limit",
    weeklyLimit: "Weekly stake limit",
    startNow: "Let's start!",
    bankroll: "Bankroll",
    newBankroll: "New bankroll",
    bankrollsLabel: "Bankrolls",
    renameBankroll: "Rename bankroll",
    deleteBankroll: "Delete bankroll",
    confirmDeleteBankroll: "Are you sure you want to delete the {name} bankroll? All related bets will be permanently removed. This cannot be undone.",
    canNotDelete: "Could not delete",
    booked: "Bankroll created",
    renamed: "Renamed",
    bankRollRemoved: "Bankroll deleted",
    validationRequired: "Enter a valid stake and odds (e.g. 1000 and 1.55)",
    validationStake: "Stake must be greater than 0 and odds at least 1.00",
    dailyLimitExceeded: "You exceeded the daily stake limit!",
    weeklyLimitExceeded: "You exceeded the weekly stake limit!",
    dailyLimitNear: "You are approaching the daily stake limit",
    weeklyLimitNear: "You are approaching the weekly stake limit",
    betSaved: "Bet recorded",
    betUpdated: "Bet updated",
    betDeleted: "Bet deleted",
    addBetDetails: "Add the bet details. Profit is calculated automatically based on the result.",
    editBet: "Edit bet",
    betDetails: "Pick / event",
    selectionExample: "e.g. Arsenal vs Chelsea, home win",
    bookmakerExample: "e.g. Bet365",
    oddsExample: "e.g. 1.95",
    bankrollCreateFailed: "Could not create the bankroll",
    bankrollDeleteFailed: "Could not delete the bankroll",
    bankrollNameRequired: "Enter a bankroll name",
    bankrollPlaceholder: "e.g. Football fund",
    dailyLimitExceededMessage: "You exceeded your daily stake limit. Please bet responsibly!",
    weeklyLimitExceededMessage: "You exceeded your weekly stake limit. Please bet responsibly!",
    dailyLimitNearMessage: "You are approaching your daily stake limit ({percent}%). Please keep your stakes in check.",
    weeklyLimitNearMessage: "You are approaching your weekly stake limit ({percent}%).",
    market: "Market",
    bookmaker: "Bookmaker",
    note: "Note",
    optionalNote: "Optional note…",
    saveBet: "Record",
    setGoalInSettings: "Set a profit goal in Settings.",
    profitLoss: "Profit / Loss",
    roi: "ROI",
    winRate: "Win rate",
    winningStreak: "Winning streak",
    losingStreak: "Losing streak",
    bankrollCurve: "Bankroll curve",
    profitGoalCard: "Profit goal",
    setGoalPrompt: "Set a profit goal in Settings.",
    dailyStakeLimit: "Daily stake limit",
    weeklyStakeLimit: "Weekly stake limit",
    yield: "Yield",
    totalSettled: "Settled bets",
    avgOdds: "Average odds",
    amountStaked: "staked",
    trade: "Trade",
    new: "New",
    editing: "Edit",
    month: "Month",
    year: "Year",
    period: "Period",
    allTime: "Full period",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    last90Days: "Last 90 days",
    currentMonth: "Current month",
    currentYear: "Current year",
    customRange: "Custom range",
    tx: "count",
    sport: "Sport",
    "Labdarúgás": "Football",
    "Kosárlabda": "Basketball",
    "Tenisz": "Tennis",
    "Jégkorong": "Ice hockey",
    "Amerikai foci": "American football",
    "Baseball": "Baseball",
    "MMA / Ökölvívás": "MMA / Boxing",
    "eSport": "eSports",
    "Egyéb": "Other",
    "Meccs kimenetel": "Match result",
    "Hendikep": "Handicap",
    "Over / Under": "Over / Under",
    "Mindkét csapat gólt szerez": "Both teams to score",
    "Szöglet": "Corners",
    "Kombi": "Accumulator",
    "Függőben": "Pending",
    "Nyert": "Won",
    "Vesztett": "Lost",
    "Fél nyerés": "Half won",
    "Fél vesztés": "Half lost",
    "Érvénytelen": "Void",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = typeof window !== "undefined" ? window.localStorage.getItem(STORAGE_KEY) : null;
    return saved === "en" || saved === "hu" ? saved : "en";
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    locale: language === "en" ? "en-US" : "hu-HU",
    t: (key, fallback = key) => DICTIONARY[language]?.[key] || DICTIONARY.hu[key] || fallback,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export default LanguageContext;
