"""initial schema

Revision ID: 163d14bd6f54
Revises:
Create Date: 2026-10-08 10:11:15.968233

"""
from alembic import op
import sqlalchemy as sa


revision = '163d14bd6f54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('picture', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auth_provider in ('email','google')", name='ck_users_auth_provider'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('bankrolls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('starting_bankroll', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('unit_size', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('profit_goal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('weekly_limit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_bankrolls_user_created', 'bankrolls', ['user_id', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('pdf_data', sa.LargeBinary(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_reports_user_created', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bankroll_id', sa.BigInteger(), nullable=False),
    sa.Column('bet_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sport', sa.String(length=80), nullable=False),
    sa.Column('market', sa.String(length=120), nullable=False),
    sa.Column('selection', sa.Text(), nullable=False),
    sa.Column('stake', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('units', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('bookmaker', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('profit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result in ('win','lose','void','half_win','half_lose','pending')", name='ck_bets_result'),
    sa.ForeignKeyConstraint(['bankroll_id'], ['bankrolls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_bets_bankroll_id', 'bets', ['bankroll_id'], unique=False)
    op.create_index('ix_bets_user_bankroll_date', 'bets', ['user_id', 'bankroll_id', 'bet_date'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('active_bankroll_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_bankroll_id'], ['bankrolls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_index('ix_bets_user_bankroll_date', table_name='bets')
    op.drop_index('ix_bets_bankroll_id', table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_reports_user_created', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_bankrolls_user_created', table_name='bankrolls')
    op.drop_table('bankrolls')
    op.drop_table('users')
    # ### end Alembic commands ###
